import type { RecipeLike } from '@/lib/domain/types'
import { RECIPE_TIPS } from './recipe-tips'

/**
 * Базова книга рецептів для demo mode.
 * У live-режимі агент доповнює її згенерованими Claude рецептами,
 * але ці лишаються як детермінована основа демонстрації.
 *
 * Поради живуть в окремому файлі (`recipe-tips.ts`) і приклеюються нижче:
 * рецепт — це дані, порада — це знання, і ростуть вони з різною швидкістю.
 */
const RAW_RECIPES: RecipeLike[] = [
  {
    id: 'r-pasta-spinach',
    slug: 'pasta-shpynat-pomidory',
    title: 'Паста зі шпинатом і помідорами',
    summary: 'Швидка вечеря з того, що вже є вдома. Шпинат встигає піти у справу.',
    servings: 2,
    cookingTime: 25,
    difficulty: 'easy',
    cuisine: 'Італійська',
    mealType: 'dinner',
    imageEmoji: '🍝',
    tags: ['vegetarian', 'kid-friendly', 'quick'],
    nutrition: { kcal: 520, protein: 18, fat: 16, carbs: 74 },
    ingredients: [
      { name: 'Макарони', normalizedName: 'макарони', quantity: 250, unit: 'г', approxPricePerUnit: 8 },
      { name: 'Шпинат', normalizedName: 'шпинат', quantity: 150, unit: 'г', approxPricePerUnit: 30, substitutes: ['салат'] },
      { name: 'Помідори', normalizedName: 'помідори', quantity: 3, unit: 'шт', approxPricePerUnit: 1200 },
      { name: 'Часник', normalizedName: 'часник', quantity: 2, unit: 'шт', approxPricePerUnit: 300, optional: true },
      { name: 'Олія', normalizedName: 'олія', quantity: 2, unit: 'ст.л', approxPricePerUnit: 6 },
      { name: 'Сир твердий', normalizedName: 'сир твердий', quantity: 50, unit: 'г', approxPricePerUnit: 45, optional: true },
    ],
    steps: [
      { step: 1, text: 'Закипʼятіть підсолену воду і відваріть макарони до al dente.', timerMinutes: 9 },
      { step: 2, text: 'Наріжте помідори кубиком, часник — тонкими пластинками.' },
      { step: 3, text: 'Розігрійте олію, обсмажте часник 30 секунд, додайте помідори.', timerMinutes: 4 },
      { step: 4, text: 'Додайте шпинат і готуйте, доки він не осяде.', timerMinutes: 3 },
      { step: 5, text: 'Змішайте з макаронами, за бажанням присипте тертим сиром.' },
    ],
  },
  {
    id: 'r-frittata',
    slug: 'frytata-zi-shpynatom',
    title: 'Фрітата зі шпинатом',
    summary: 'Пʼять інгредієнтів, одна сковорідка, 20 хвилин.',
    servings: 2,
    cookingTime: 20,
    difficulty: 'easy',
    cuisine: 'Італійська',
    mealType: 'dinner',
    imageEmoji: '🍳',
    tags: ['vegetarian', 'kid-friendly', 'quick', 'high-protein'],
    nutrition: { kcal: 340, protein: 24, fat: 23, carbs: 6 },
    ingredients: [
      { name: 'Яйця', normalizedName: 'яйця', quantity: 4, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Шпинат', normalizedName: 'шпинат', quantity: 120, unit: 'г', approxPricePerUnit: 30 },
      { name: 'Молоко', normalizedName: 'молоко', quantity: 60, unit: 'мл', approxPricePerUnit: 5 },
      { name: 'Масло вершкове', normalizedName: 'масло вершкове', quantity: 20, unit: 'г', approxPricePerUnit: 40 },
      { name: 'Помідори', normalizedName: 'помідори', quantity: 2, unit: 'шт', approxPricePerUnit: 1200, optional: true },
      { name: 'Сир твердий', normalizedName: 'сир твердий', quantity: 40, unit: 'г', approxPricePerUnit: 45, optional: true },
    ],
    steps: [
      { step: 1, text: 'Збийте яйця з молоком, посоліть.' },
      { step: 2, text: 'Розтопіть масло, підсмажте шпинат до розмʼякшення.', timerMinutes: 3 },
      { step: 3, text: 'Влийте яйця, готуйте на малому вогні під кришкою.', timerMinutes: 10 },
      { step: 4, text: 'За бажанням додайте помідори й сир, дайте розплавитись.', timerMinutes: 2 },
    ],
  },
  {
    id: 'r-tiramisu',
    slug: 'tiramisu',
    title: 'Тірамісу',
    summary: 'Класичний італійський десерт із маскарпоне та кавою. Без випікання.',
    servings: 6,
    cookingTime: 30,
    difficulty: 'medium',
    cuisine: 'Італійська',
    mealType: 'dessert',
    imageEmoji: '🍰',
    tags: ['dessert', 'no-bake', 'coffee'],
    nutrition: { kcal: 450, protein: 8, fat: 28, carbs: 40 },
    ingredients: [
      { name: 'Маскарпоне', normalizedName: 'маскарпоне', quantity: 500, unit: 'г', approxPricePerUnit: 60 },
      { name: 'Печиво савоярді', normalizedName: 'савоярді', quantity: 200, unit: 'г', approxPricePerUnit: 50 },
      { name: 'Яйця', normalizedName: 'яйця', quantity: 4, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Цукор', normalizedName: 'цукор', quantity: 100, unit: 'г', approxPricePerUnit: 4 },
      // мелена кава вимірюється у грамах: 30 г дають ~300 мл міцної кави.
      // Тримати тут «300 мл» означало б порівнювати обʼєм напою з масою упаковки.
      { name: 'Кава мелена', normalizedName: 'кава', quantity: 30, unit: 'г', approxPricePerUnit: 60 },
      { name: 'Какао', normalizedName: 'какао', quantity: 20, unit: 'г', approxPricePerUnit: 55 },
    ],
    steps: [
      { step: 1, text: 'Зваріть із 30 г меленої кави ~300 мл міцної кави і повністю охолодіть.', timerMinutes: 10 },
      { step: 2, text: 'Відділіть жовтки, збийте їх із цукром до світлої маси.', timerMinutes: 5 },
      { step: 3, text: 'Вмішайте маскарпоне до однорідності.' },
      { step: 4, text: 'Збийте білки до стійких піків і обережно вмішайте в крем.', timerMinutes: 4 },
      { step: 5, text: 'Занурюйте савоярді в каву на 1–2 секунди й викладайте шаром.' },
      { step: 6, text: 'Чергуйте крем і печиво, зверху присипте какао.' },
      { step: 7, text: 'Охолоджуйте в холодильнику щонайменше 4 години.', timerMinutes: 240 },
    ],
  },
  {
    id: 'r-omlet',
    slug: 'omlet-z-pomidoramy',
    title: 'Омлет з помідорами',
    summary: 'Найшвидший спосіб нагодувати родину з того, що є в холодильнику.',
    servings: 2,
    cookingTime: 12,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'breakfast',
    imageEmoji: '🍳',
    tags: ['vegetarian', 'kid-friendly', 'quick'],
    nutrition: { kcal: 280, protein: 18, fat: 20, carbs: 5 },
    ingredients: [
      { name: 'Яйця', normalizedName: 'яйця', quantity: 4, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Молоко', normalizedName: 'молоко', quantity: 80, unit: 'мл', approxPricePerUnit: 5 },
      { name: 'Помідори', normalizedName: 'помідори', quantity: 2, unit: 'шт', approxPricePerUnit: 1200 },
      { name: 'Масло вершкове', normalizedName: 'масло вершкове', quantity: 15, unit: 'г', approxPricePerUnit: 40 },
    ],
    steps: [
      { step: 1, text: 'Збийте яйця з молоком і дрібкою солі.' },
      { step: 2, text: 'Обсмажте помідори на маслі 2 хвилини.', timerMinutes: 2 },
      { step: 3, text: 'Влийте яєчну суміш, накрийте кришкою.', timerMinutes: 6 },
    ],
  },
  {
    id: 'r-mac-cheese',
    slug: 'makarony-z-syrom',
    title: 'Макарони із сирним соусом',
    summary: 'Дитяча класика: без гострого, готується у пʼять кроків.',
    servings: 3,
    cookingTime: 25,
    difficulty: 'easy',
    cuisine: 'Американська',
    mealType: 'lunch',
    imageEmoji: '🧀',
    tags: ['vegetarian', 'kid-friendly', 'comfort'],
    nutrition: { kcal: 610, protein: 22, fat: 26, carbs: 72 },
    ingredients: [
      { name: 'Макарони', normalizedName: 'макарони', quantity: 300, unit: 'г', approxPricePerUnit: 8 },
      { name: 'Молоко', normalizedName: 'молоко', quantity: 250, unit: 'мл', approxPricePerUnit: 5 },
      { name: 'Сир твердий', normalizedName: 'сир твердий', quantity: 150, unit: 'г', approxPricePerUnit: 45 },
      { name: 'Масло вершкове', normalizedName: 'масло вершкове', quantity: 30, unit: 'г', approxPricePerUnit: 40 },
      { name: 'Борошно', normalizedName: 'борошно', quantity: 20, unit: 'г', approxPricePerUnit: 3 },
    ],
    steps: [
      { step: 1, text: 'Відваріть макарони.', timerMinutes: 9 },
      { step: 2, text: 'Розтопіть масло, вмішайте борошно, прогрійте хвилину.', timerMinutes: 1 },
      { step: 3, text: 'Поступово влийте молоко, помішуючи до загустіння.', timerMinutes: 4 },
      { step: 4, text: 'Додайте тертий сир, розмішайте до однорідності.' },
      { step: 5, text: 'Змішайте соус із макаронами.' },
    ],
  },
  {
    id: 'r-chicken-veg',
    slug: 'kuryache-file-z-ovochamy',
    title: 'Куряче філе з овочами на сковороді',
    summary: 'Збалансована вечеря на двох за 30 хвилин.',
    servings: 2,
    cookingTime: 30,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'dinner',
    imageEmoji: '🍗',
    tags: ['high-protein', 'kid-friendly'],
    nutrition: { kcal: 430, protein: 42, fat: 15, carbs: 22 },
    ingredients: [
      { name: 'Куряче філе', normalizedName: 'куряче філе', quantity: 400, unit: 'г', approxPricePerUnit: 25 },
      { name: 'Помідори', normalizedName: 'помідори', quantity: 2, unit: 'шт', approxPricePerUnit: 1200 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 1, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Олія', normalizedName: 'олія', quantity: 2, unit: 'ст.л', approxPricePerUnit: 6 },
      { name: 'Шпинат', normalizedName: 'шпинат', quantity: 100, unit: 'г', approxPricePerUnit: 30, optional: true },
    ],
    steps: [
      { step: 1, text: 'Наріжте філе смужками, посоліть.' },
      { step: 2, text: 'Обсмажте на сильному вогні до рум’яності.', timerMinutes: 7 },
      { step: 3, text: 'Додайте цибулю й помідори, тушкуйте.', timerMinutes: 10 },
      { step: 4, text: 'Наприкінці вкиньте шпинат і вимкніть вогонь.', timerMinutes: 2 },
    ],
  },
  {
    id: 'r-syrnyky',
    slug: 'syrnyky',
    title: 'Сирники',
    summary: 'Сніданок, який любить уся родина.',
    servings: 3,
    cookingTime: 25,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'breakfast',
    imageEmoji: '🥞',
    tags: ['vegetarian', 'kid-friendly', 'sweet'],
    nutrition: { kcal: 390, protein: 24, fat: 14, carbs: 40 },
    ingredients: [
      { name: 'Сир кисломолочний', normalizedName: 'сир кисломолочний', quantity: 400, unit: 'г', approxPricePerUnit: 20 },
      { name: 'Яйця', normalizedName: 'яйця', quantity: 2, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Борошно', normalizedName: 'борошно', quantity: 60, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Цукор', normalizedName: 'цукор', quantity: 40, unit: 'г', approxPricePerUnit: 4 },
      { name: 'Сметана', normalizedName: 'сметана', quantity: 100, unit: 'г', approxPricePerUnit: 15, optional: true },
    ],
    steps: [
      { step: 1, text: 'Розімніть сир з яйцями та цукром.' },
      { step: 2, text: 'Додайте борошно, замісіть мʼяке тісто.' },
      { step: 3, text: 'Сформуйте сирники й обсмажте з двох боків.', timerMinutes: 10 },
    ],
  },
  {
    id: 'r-spicy-noodles',
    slug: 'gostri-locshyna',
    title: 'Гостра локшина по-азійськи',
    summary: 'Для тих, хто любить гостре. Готується за 20 хвилин.',
    servings: 2,
    cookingTime: 20,
    difficulty: 'easy',
    cuisine: 'Азійська',
    mealType: 'dinner',
    imageEmoji: '🌶️',
    tags: ['spicy', 'quick'],
    nutrition: { kcal: 480, protein: 16, fat: 14, carbs: 72 },
    ingredients: [
      { name: 'Макарони', normalizedName: 'макарони', quantity: 200, unit: 'г', approxPricePerUnit: 8 },
      { name: 'Куряче філе', normalizedName: 'куряче філе', quantity: 200, unit: 'г', approxPricePerUnit: 25 },
      { name: 'Соєвий соус', normalizedName: 'соєвий соус', quantity: 40, unit: 'мл', approxPricePerUnit: 20 },
      { name: 'Часник', normalizedName: 'часник', quantity: 3, unit: 'шт', approxPricePerUnit: 300 },
    ],
    steps: [
      { step: 1, text: 'Відваріть локшину.', timerMinutes: 7 },
      { step: 2, text: 'Обсмажте курку з часником і гострим перцем.', timerMinutes: 8 },
      { step: 3, text: 'Змішайте все із соєвим соусом.' },
    ],
  },
  // ─────────────────────── Обіди ───────────────────────
  {
    id: 'r-borshch',
    slug: 'borshch-ukrainskyi',
    title: 'Борщ український',
    summary: 'Класика, яка годує родину два дні. Готується довго, але майже без участі.',
    servings: 6,
    cookingTime: 90,
    difficulty: 'medium',
    cuisine: 'Українська',
    mealType: 'lunch',
    imageEmoji: '🍲',
    tags: ['comfort', 'batch-cook'],
    nutrition: { kcal: 320, protein: 14, fat: 12, carbs: 38 },
    ingredients: [
      { name: 'Буряк', normalizedName: 'буряк', quantity: 400, unit: 'г', approxPricePerUnit: 4 },
      { name: 'Картопля', normalizedName: 'картопля', quantity: 500, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Капуста', normalizedName: 'капуста', quantity: 300, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Морква', normalizedName: 'морква', quantity: 150, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 1, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Томатна паста', normalizedName: 'томатна паста', quantity: 60, unit: 'г', approxPricePerUnit: 12 },
      { name: 'Сметана', normalizedName: 'сметана', quantity: 100, unit: 'г', approxPricePerUnit: 15, optional: true },
      { name: 'Часник', normalizedName: 'часник', quantity: 3, unit: 'шт', approxPricePerUnit: 300, optional: true },
    ],
    steps: [
      { step: 1, text: 'Зваріть бульйон або доведіть до кипіння 2,5 л води.', timerMinutes: 15 },
      { step: 2, text: 'Наріжте картоплю кубиком і закиньте у воду.', timerMinutes: 10 },
      { step: 3, text: 'Натріть буряк і моркву, обсмажте з цибулею й томатною пастою.', timerMinutes: 12 },
      { step: 4, text: 'Додайте нашатковану капусту, варіть до мʼякості.', timerMinutes: 10 },
      { step: 5, text: 'Викладіть засмажку, доваріть 5 хвилин і дайте настоятись.', timerMinutes: 20 },
    ],
  },
  {
    id: 'r-soup-chicken',
    slug: 'kuriachyi-sup-z-lokshynoiu',
    title: 'Курячий суп з локшиною',
    summary: 'Тепла страва, яку люблять діти. Один каструль, мінімум рухів.',
    servings: 4,
    cookingTime: 40,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'lunch',
    imageEmoji: '🍜',
    tags: ['kid-friendly', 'comfort'],
    nutrition: { kcal: 280, protein: 22, fat: 8, carbs: 30 },
    ingredients: [
      { name: 'Куряче філе', normalizedName: 'куряче філе', quantity: 300, unit: 'г', approxPricePerUnit: 25 },
      { name: 'Макарони', normalizedName: 'макарони', quantity: 120, unit: 'г', approxPricePerUnit: 8 },
      { name: 'Картопля', normalizedName: 'картопля', quantity: 300, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Морква', normalizedName: 'морква', quantity: 100, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 1, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Кріп', normalizedName: 'кріп', quantity: 20, unit: 'г', approxPricePerUnit: 25, optional: true },
    ],
    steps: [
      { step: 1, text: 'Відваріть філе 20 хвилин, дістаньте й наріжте.', timerMinutes: 20 },
      { step: 2, text: 'У бульйон закиньте картоплю й моркву.', timerMinutes: 12 },
      { step: 3, text: 'Додайте локшину та мʼясо, варіть до готовності.', timerMinutes: 7 },
    ],
  },
  {
    id: 'r-plov',
    slug: 'plov-z-kurkoiu',
    title: 'Плов з куркою',
    summary: 'Ситна страва на всю родину з одного казана.',
    servings: 4,
    cookingTime: 55,
    difficulty: 'medium',
    cuisine: 'Азійська',
    mealType: 'lunch',
    imageEmoji: '🍛',
    tags: ['comfort', 'batch-cook'],
    nutrition: { kcal: 520, protein: 26, fat: 18, carbs: 62 },
    ingredients: [
      { name: 'Рис', normalizedName: 'рис', quantity: 400, unit: 'г', approxPricePerUnit: 6 },
      { name: 'Куряче філе', normalizedName: 'куряче філе', quantity: 500, unit: 'г', approxPricePerUnit: 25 },
      { name: 'Морква', normalizedName: 'морква', quantity: 300, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 2, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Олія', normalizedName: 'олія', quantity: 4, unit: 'ст.л', approxPricePerUnit: 6 },
      { name: 'Часник', normalizedName: 'часник', quantity: 4, unit: 'шт', approxPricePerUnit: 300 },
    ],
    steps: [
      { step: 1, text: 'Обсмажте мʼясо на сильному вогні до скоринки.', timerMinutes: 8 },
      { step: 2, text: 'Додайте цибулю й моркву соломкою, тушкуйте.', timerMinutes: 10 },
      { step: 3, text: 'Всипте промитий рис, залийте окропом на 2 см вище.', timerMinutes: 2 },
      { step: 4, text: 'Варіть під кришкою на малому вогні, не мішаючи.', timerMinutes: 25 },
    ],
  },
  {
    id: 'r-salad-greek',
    slug: 'grecki-salat',
    title: 'Грецький салат',
    summary: 'Пʼять хвилин, жодного вогню. Ідеально, коли овочі треба зʼїсти сьогодні.',
    servings: 2,
    cookingTime: 10,
    difficulty: 'easy',
    cuisine: 'Середземноморська',
    mealType: 'lunch',
    imageEmoji: '🥗',
    tags: ['vegetarian', 'quick', 'no-cook'],
    nutrition: { kcal: 210, protein: 8, fat: 16, carbs: 10 },
    ingredients: [
      { name: 'Помідори', normalizedName: 'помідори', quantity: 3, unit: 'шт', approxPricePerUnit: 1200 },
      { name: 'Огірки', normalizedName: 'огірки', quantity: 2, unit: 'шт', approxPricePerUnit: 1000 },
      { name: 'Сир твердий', normalizedName: 'сир твердий', quantity: 100, unit: 'г', approxPricePerUnit: 45, substitutes: ['сир кисломолочний'] },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 1, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Олія', normalizedName: 'олія', quantity: 2, unit: 'ст.л', approxPricePerUnit: 6 },
    ],
    steps: [
      { step: 1, text: 'Наріжте овочі великими кубиками.' },
      { step: 2, text: 'Додайте сир, полийте олією, перемішайте.' },
    ],
  },

  // ─────────────────────── Вечері ───────────────────────
  {
    id: 'r-deruny',
    slug: 'deruny',
    title: 'Деруни',
    summary: 'Коли є картопля і треба нагодувати всіх швидко й ситно.',
    servings: 3,
    cookingTime: 35,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'dinner',
    imageEmoji: '🥔',
    tags: ['vegetarian', 'kid-friendly', 'comfort'],
    nutrition: { kcal: 400, protein: 10, fat: 18, carbs: 50 },
    ingredients: [
      { name: 'Картопля', normalizedName: 'картопля', quantity: 800, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Яйця', normalizedName: 'яйця', quantity: 1, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Борошно', normalizedName: 'борошно', quantity: 40, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 1, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Олія', normalizedName: 'олія', quantity: 4, unit: 'ст.л', approxPricePerUnit: 6 },
      { name: 'Сметана', normalizedName: 'сметана', quantity: 100, unit: 'г', approxPricePerUnit: 15, optional: true },
    ],
    steps: [
      { step: 1, text: 'Натріть картоплю й цибулю, злийте зайву рідину.', timerMinutes: 8 },
      { step: 2, text: 'Додайте яйце й борошно, посоліть.' },
      { step: 3, text: 'Смажте на олії до рум’яної скоринки з двох боків.', timerMinutes: 15 },
    ],
  },
  {
    id: 'r-kotlety',
    slug: 'domashni-kotlety',
    title: 'Домашні котлети з пюре',
    summary: 'Те, що просять діти. Робиться партією і йде на два прийоми.',
    servings: 4,
    cookingTime: 50,
    difficulty: 'medium',
    cuisine: 'Українська',
    mealType: 'dinner',
    imageEmoji: '🍽️',
    tags: ['kid-friendly', 'comfort', 'batch-cook'],
    nutrition: { kcal: 540, protein: 30, fat: 26, carbs: 45 },
    ingredients: [
      { name: 'Фарш', normalizedName: 'фарш', quantity: 500, unit: 'г', approxPricePerUnit: 22 },
      { name: 'Картопля', normalizedName: 'картопля', quantity: 700, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Яйця', normalizedName: 'яйця', quantity: 1, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 1, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Хліб', normalizedName: 'хліб', quantity: 60, unit: 'г', approxPricePerUnit: 6 },
      { name: 'Молоко', normalizedName: 'молоко', quantity: 100, unit: 'мл', approxPricePerUnit: 5 },
      { name: 'Масло вершкове', normalizedName: 'масло вершкове', quantity: 30, unit: 'г', approxPricePerUnit: 40 },
    ],
    steps: [
      { step: 1, text: 'Замочіть хліб у молоці, віджміть і додайте до фаршу з цибулею та яйцем.' },
      { step: 2, text: 'Сформуйте котлети й обсмажте до скоринки.', timerMinutes: 12 },
      { step: 3, text: 'Долийте трохи води, тушкуйте під кришкою.', timerMinutes: 15 },
      { step: 4, text: 'Відваріть картоплю, розімніть із маслом і молоком.', timerMinutes: 20 },
    ],
  },
  {
    id: 'r-fish-oven',
    slug: 'ryba-v-dukhovtsi',
    title: 'Риба з овочами в духовці',
    summary: 'Поставив і забув. Мінімум посуду, максимум користі.',
    servings: 2,
    cookingTime: 40,
    difficulty: 'easy',
    cuisine: 'Середземноморська',
    mealType: 'dinner',
    imageEmoji: '🐟',
    tags: ['high-protein', 'healthy'],
    nutrition: { kcal: 380, protein: 34, fat: 18, carbs: 16 },
    ingredients: [
      { name: 'Риба', normalizedName: 'риба', quantity: 400, unit: 'г', approxPricePerUnit: 35 },
      { name: 'Картопля', normalizedName: 'картопля', quantity: 400, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Помідори', normalizedName: 'помідори', quantity: 2, unit: 'шт', approxPricePerUnit: 1200 },
      { name: 'Лимон', normalizedName: 'лимон', quantity: 1, unit: 'шт', approxPricePerUnit: 1500, optional: true },
      { name: 'Олія', normalizedName: 'олія', quantity: 2, unit: 'ст.л', approxPricePerUnit: 6 },
    ],
    steps: [
      { step: 1, text: 'Наріжте картоплю тонкими скибками, викладіть на деко.' },
      { step: 2, text: 'Зверху покладіть рибу й помідори, полийте олією.' },
      { step: 3, text: 'Запікайте при 200 °C.', timerMinutes: 30 },
    ],
  },
  {
    id: 'r-veg-stew',
    slug: 'ovocheve-rahu',
    title: 'Овочеве рагу',
    summary: 'Рятівник для овочів, які треба використати просто зараз.',
    servings: 4,
    cookingTime: 35,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'dinner',
    imageEmoji: '🥘',
    tags: ['vegetarian', 'vegan', 'healthy', 'rescue'],
    nutrition: { kcal: 220, protein: 6, fat: 9, carbs: 30 },
    ingredients: [
      { name: 'Кабачки', normalizedName: 'кабачки', quantity: 300, unit: 'г', approxPricePerUnit: 4 },
      { name: 'Картопля', normalizedName: 'картопля', quantity: 300, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Морква', normalizedName: 'морква', quantity: 150, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Помідори', normalizedName: 'помідори', quantity: 2, unit: 'шт', approxPricePerUnit: 1200 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 1, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Олія', normalizedName: 'олія', quantity: 2, unit: 'ст.л', approxPricePerUnit: 6 },
      { name: 'Перець', normalizedName: 'перець', quantity: 1, unit: 'шт', approxPricePerUnit: 1500, optional: true },
    ],
    steps: [
      { step: 1, text: 'Наріжте всі овочі кубиком приблизно одного розміру.' },
      { step: 2, text: 'Обсмажте цибулю з морквою, додайте решту.', timerMinutes: 8 },
      { step: 3, text: 'Тушкуйте під кришкою до мʼякості.', timerMinutes: 20 },
    ],
  },
  {
    id: 'r-mushroom-risotto',
    slug: 'ryzotto-z-hrybamy',
    title: 'Різотто з грибами',
    summary: 'Потребує уваги біля плити, зате результат ресторанного рівня.',
    servings: 2,
    cookingTime: 45,
    difficulty: 'hard',
    cuisine: 'Італійська',
    mealType: 'dinner',
    imageEmoji: '🍚',
    tags: ['vegetarian', 'special'],
    nutrition: { kcal: 480, protein: 14, fat: 18, carbs: 64 },
    ingredients: [
      { name: 'Рис', normalizedName: 'рис', quantity: 200, unit: 'г', approxPricePerUnit: 6 },
      { name: 'Гриби', normalizedName: 'гриби', quantity: 300, unit: 'г', approxPricePerUnit: 12 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 1, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Масло вершкове', normalizedName: 'масло вершкове', quantity: 40, unit: 'г', approxPricePerUnit: 40 },
      { name: 'Сир твердий', normalizedName: 'сир твердий', quantity: 60, unit: 'г', approxPricePerUnit: 45 },
      { name: 'Вершки', normalizedName: 'вершки', quantity: 100, unit: 'мл', approxPricePerUnit: 12, optional: true, substitutes: ['сметана'] },
    ],
    steps: [
      { step: 1, text: 'Обсмажте гриби окремо до випаровування рідини.', timerMinutes: 10 },
      { step: 2, text: 'Спасеруйте цибулю, всипте рис, прогрійте 2 хвилини.', timerMinutes: 2 },
      { step: 3, text: 'Додавайте гарячий бульйон по черпаку, помішуючи.', timerMinutes: 20 },
      { step: 4, text: 'Вмішайте масло й тертий сир, дайте постояти 2 хвилини.', timerMinutes: 2 },
    ],
  },

  // ─────────────────────── Сніданки ───────────────────────
  {
    id: 'r-oatmeal',
    slug: 'vivsianka-z-fruktamy',
    title: 'Вівсянка з фруктами',
    summary: 'Сніданок за десять хвилин із того, що майже завжди є вдома.',
    servings: 2,
    cookingTime: 12,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'breakfast',
    imageEmoji: '🥣',
    tags: ['vegetarian', 'healthy', 'quick', 'kid-friendly'],
    nutrition: { kcal: 300, protein: 11, fat: 8, carbs: 48 },
    ingredients: [
      { name: 'Вівсянка', normalizedName: 'вівсянка', quantity: 120, unit: 'г', approxPricePerUnit: 5 },
      { name: 'Молоко', normalizedName: 'молоко', quantity: 400, unit: 'мл', approxPricePerUnit: 5 },
      { name: 'Банани', normalizedName: 'банани', quantity: 1, unit: 'шт', approxPricePerUnit: 1200, optional: true },
      { name: 'Мед', normalizedName: 'мед', quantity: 20, unit: 'г', approxPricePerUnit: 25, optional: true },
    ],
    steps: [
      { step: 1, text: 'Доведіть молоко до кипіння, всипте пластівці.', timerMinutes: 2 },
      { step: 2, text: 'Варіть на малому вогні, помішуючи.', timerMinutes: 6 },
      { step: 3, text: 'Додайте фрукти й мед за смаком.' },
    ],
  },
  {
    id: 'r-avocado-toast',
    slug: 'tosty-z-avokado',
    title: 'Тости з авокадо та яйцем',
    summary: 'Швидкий білковий сніданок без готування як такого.',
    servings: 2,
    cookingTime: 15,
    difficulty: 'easy',
    cuisine: 'Американська',
    mealType: 'breakfast',
    imageEmoji: '🥑',
    tags: ['vegetarian', 'healthy', 'quick'],
    nutrition: { kcal: 380, protein: 16, fat: 24, carbs: 28 },
    ingredients: [
      { name: 'Хліб', normalizedName: 'хліб', quantity: 4, unit: 'шт', approxPricePerUnit: 600 },
      { name: 'Авокадо', normalizedName: 'авокадо', quantity: 1, unit: 'шт', approxPricePerUnit: 6000 },
      { name: 'Яйця', normalizedName: 'яйця', quantity: 2, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Лимон', normalizedName: 'лимон', quantity: 1, unit: 'шт', approxPricePerUnit: 1500, optional: true },
    ],
    steps: [
      { step: 1, text: 'Підсмажте хліб у тостері або на сухій сковороді.', timerMinutes: 3 },
      { step: 2, text: 'Розімніть авокадо з соком лимона й сіллю.' },
      { step: 3, text: 'Приготуйте яйця пашот або смажені.', timerMinutes: 5 },
    ],
  },
  {
    id: 'r-mlyntsi',
    slug: 'mlyntsi',
    title: 'Млинці',
    summary: 'Вихідний сніданок, який діти памʼятають роками.',
    servings: 4,
    cookingTime: 35,
    difficulty: 'medium',
    cuisine: 'Українська',
    mealType: 'breakfast',
    imageEmoji: '🥞',
    tags: ['vegetarian', 'kid-friendly', 'sweet'],
    nutrition: { kcal: 340, protein: 12, fat: 10, carbs: 50 },
    ingredients: [
      { name: 'Борошно', normalizedName: 'борошно', quantity: 250, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Молоко', normalizedName: 'молоко', quantity: 500, unit: 'мл', approxPricePerUnit: 5 },
      { name: 'Яйця', normalizedName: 'яйця', quantity: 3, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Цукор', normalizedName: 'цукор', quantity: 30, unit: 'г', approxPricePerUnit: 4 },
      { name: 'Олія', normalizedName: 'олія', quantity: 2, unit: 'ст.л', approxPricePerUnit: 6 },
    ],
    steps: [
      { step: 1, text: 'Збийте яйця з цукром, влийте молоко.' },
      { step: 2, text: 'Просійте борошно, замісіть рідке тісто без грудок.', timerMinutes: 5 },
      { step: 3, text: 'Смажте на розігрітій сковороді з обох боків.', timerMinutes: 20 },
    ],
  },

  // ─────────────────────── Десерти й перекуси ───────────────────────
  {
    id: 'r-cheese-bake',
    slug: 'syrna-zapikanka',
    title: 'Сирна запіканка',
    summary: 'Рятує сир, якому лишився день. Готується сама в духовці.',
    servings: 4,
    cookingTime: 50,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'dessert',
    imageEmoji: '🍮',
    tags: ['vegetarian', 'kid-friendly', 'sweet', 'rescue'],
    nutrition: { kcal: 300, protein: 20, fat: 12, carbs: 30 },
    ingredients: [
      { name: 'Сир кисломолочний', normalizedName: 'сир кисломолочний', quantity: 500, unit: 'г', approxPricePerUnit: 20 },
      { name: 'Яйця', normalizedName: 'яйця', quantity: 3, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Цукор', normalizedName: 'цукор', quantity: 80, unit: 'г', approxPricePerUnit: 4 },
      { name: 'Борошно', normalizedName: 'борошно', quantity: 60, unit: 'г', approxPricePerUnit: 3, substitutes: ['манка'] },
      { name: 'Сметана', normalizedName: 'сметана', quantity: 100, unit: 'г', approxPricePerUnit: 15, optional: true },
      { name: 'Родзинки', normalizedName: 'родзинки', quantity: 50, unit: 'г', approxPricePerUnit: 20, optional: true },
    ],
    steps: [
      { step: 1, text: 'Розітріть сир з яйцями та цукром до однорідності.' },
      { step: 2, text: 'Вмішайте борошно й родзинки, викладіть у форму.' },
      { step: 3, text: 'Випікайте при 180 °C до золотистої скоринки.', timerMinutes: 40 },
    ],
  },
  {
    id: 'r-hummus',
    slug: 'hummus',
    title: 'Хумус',
    summary: 'Перекус, який стоїть у холодильнику три дні й не набридає.',
    servings: 4,
    cookingTime: 15,
    difficulty: 'easy',
    cuisine: 'Середземноморська',
    mealType: 'snack',
    imageEmoji: '🫓',
    tags: ['vegetarian', 'vegan', 'healthy', 'no-cook'],
    nutrition: { kcal: 240, protein: 9, fat: 14, carbs: 22 },
    ingredients: [
      { name: 'Нут', normalizedName: 'нут', quantity: 400, unit: 'г', approxPricePerUnit: 8 },
      { name: 'Часник', normalizedName: 'часник', quantity: 2, unit: 'шт', approxPricePerUnit: 300 },
      { name: 'Олія', normalizedName: 'олія', quantity: 3, unit: 'ст.л', approxPricePerUnit: 6 },
      { name: 'Лимон', normalizedName: 'лимон', quantity: 1, unit: 'шт', approxPricePerUnit: 1500 },
      { name: 'Хліб', normalizedName: 'хліб', quantity: 4, unit: 'шт', approxPricePerUnit: 600, optional: true },
    ],
    steps: [
      { step: 1, text: 'Злийте рідину з нуту, лишивши трохи для консистенції.' },
      { step: 2, text: 'Збийте блендером із часником, олією та соком лимона.', timerMinutes: 5 },
      { step: 3, text: 'Подавайте з підсушеним хлібом.' },
    ],
  },
  {
    id: 'r-varenyky',
    slug: 'varenyky-z-kartopleiu',
    title: 'Вареники з картоплею',
    summary: 'Довго, але на дві вечері. Робиться партією і морозиться.',
    servings: 4,
    cookingTime: 80,
    difficulty: 'hard',
    cuisine: 'Українська',
    mealType: 'dinner',
    imageEmoji: '🥟',
    tags: ['vegetarian', 'comfort', 'batch-cook', 'kid-friendly'],
    nutrition: { kcal: 460, protein: 12, fat: 12, carbs: 76 },
    ingredients: [
      { name: 'Борошно', normalizedName: 'борошно', quantity: 400, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Картопля', normalizedName: 'картопля', quantity: 700, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 2, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Яйця', normalizedName: 'яйця', quantity: 1, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Олія', normalizedName: 'олія', quantity: 3, unit: 'ст.л', approxPricePerUnit: 6 },
      { name: 'Сметана', normalizedName: 'сметана', quantity: 150, unit: 'г', approxPricePerUnit: 15, optional: true },
    ],
    steps: [
      { step: 1, text: 'Замісіть тісто з борошна, яйця, окропу та щіпки солі. Накрийте й лишіть відпочити.', timerMinutes: 30 },
      { step: 2, text: 'Відваріть картоплю, розімніть із засмаженою цибулею.', timerMinutes: 25 },
      { step: 3, text: 'Розкачайте тісто, виріжте кружечки, наповніть і защипніть.', timerMinutes: 20 },
      { step: 4, text: 'Варіть у підсоленій воді 3–4 хвилини після спливання.', timerMinutes: 5 },
    ],
  },
  {
    id: 'r-zapikanka-ovochi',
    slug: 'ovocheva-zapikanka-z-syrom',
    title: 'Овочева запіканка з сиром',
    summary: 'Ставите в духовку — і тридцять хвилин вільні.',
    servings: 4,
    cookingTime: 45,
    difficulty: 'easy',
    cuisine: 'Середземноморська',
    mealType: 'dinner',
    imageEmoji: '🧆',
    tags: ['vegetarian', 'healthy', 'rescue'],
    nutrition: { kcal: 330, protein: 15, fat: 18, carbs: 28 },
    ingredients: [
      { name: 'Кабачки', normalizedName: 'кабачки', quantity: 400, unit: 'г', approxPricePerUnit: 4 },
      { name: 'Помідори', normalizedName: 'помідори', quantity: 3, unit: 'шт', approxPricePerUnit: 1200 },
      { name: 'Картопля', normalizedName: 'картопля', quantity: 300, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Сир твердий', normalizedName: 'сир твердий', quantity: 120, unit: 'г', approxPricePerUnit: 45 },
      { name: 'Сметана', normalizedName: 'сметана', quantity: 150, unit: 'г', approxPricePerUnit: 15 },
      { name: 'Часник', normalizedName: 'часник', quantity: 2, unit: 'шт', approxPricePerUnit: 300, optional: true },
    ],
    steps: [
      { step: 1, text: 'Наріжте всі овочі кружальцями однакової товщини.' },
      { step: 2, text: 'Викладіть шарами у форму, кожен шар трохи посоліть.' },
      { step: 3, text: 'Залийте сметаною з часником, зверху натріть сир.' },
      { step: 4, text: 'Запікайте при 190 °C до золотистої скоринки.', timerMinutes: 35 },
    ],
  },
  {
    id: 'r-kasha-hrechana',
    slug: 'hrechka-z-hrybamy',
    title: 'Гречка з грибами',
    summary: 'Проста вечеря, яка не потребує уваги і виходить смачною завжди.',
    servings: 3,
    cookingTime: 30,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'dinner',
    imageEmoji: '🍚',
    tags: ['vegetarian', 'vegan', 'healthy', 'quick'],
    nutrition: { kcal: 350, protein: 13, fat: 10, carbs: 55 },
    ingredients: [
      { name: 'Гречка', normalizedName: 'гречка', quantity: 250, unit: 'г', approxPricePerUnit: 6 },
      { name: 'Гриби', normalizedName: 'гриби', quantity: 300, unit: 'г', approxPricePerUnit: 12 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 1, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Морква', normalizedName: 'морква', quantity: 100, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Олія', normalizedName: 'олія', quantity: 3, unit: 'ст.л', approxPricePerUnit: 6 },
    ],
    steps: [
      { step: 1, text: 'Промийте гречку й залийте окропом у пропорції 1:2.', timerMinutes: 2 },
      { step: 2, text: 'Варіть під кришкою на малому вогні, не відкриваючи.', timerMinutes: 15 },
      { step: 3, text: 'Окремо обсмажте гриби з цибулею та морквою.', timerMinutes: 12 },
      { step: 4, text: 'Змішайте, накрийте й дайте постояти 5 хвилин.', timerMinutes: 5 },
    ],
  },
  {
    id: 'r-salat-olivie',
    slug: 'salat-z-kurkoiu-i-ovochamy',
    title: 'Салат із куркою та овочами',
    summary: 'Ситний салат, який замінює повноцінну вечерю.',
    servings: 3,
    cookingTime: 25,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'lunch',
    imageEmoji: '🥙',
    tags: ['high-protein', 'healthy'],
    nutrition: { kcal: 360, protein: 30, fat: 16, carbs: 20 },
    ingredients: [
      { name: 'Куряче філе', normalizedName: 'куряче філе', quantity: 300, unit: 'г', approxPricePerUnit: 25 },
      { name: 'Огірки', normalizedName: 'огірки', quantity: 2, unit: 'шт', approxPricePerUnit: 1000 },
      { name: 'Помідори', normalizedName: 'помідори', quantity: 2, unit: 'шт', approxPricePerUnit: 1200 },
      { name: 'Яйця', normalizedName: 'яйця', quantity: 2, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Сметана', normalizedName: 'сметана', quantity: 100, unit: 'г', approxPricePerUnit: 15, substitutes: ['йогурт'] },
      { name: 'Кріп', normalizedName: 'кріп', quantity: 20, unit: 'г', approxPricePerUnit: 25, optional: true },
    ],
    steps: [
      { step: 1, text: 'Відваріть філе та яйця, охолодіть.', timerMinutes: 20 },
      { step: 2, text: 'Наріжте все кубиком приблизно одного розміру.' },
      { step: 3, text: 'Заправте сметаною з кропом безпосередньо перед подачею.' },
    ],
  },
  {
    id: 'r-sup-kvasolia',
    slug: 'kvasolevyi-sup',
    title: 'Квасолевий суп',
    summary: 'Дешева, ситна й дуже поживна страва з бакалії.',
    servings: 4,
    cookingTime: 45,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'lunch',
    imageEmoji: '🥣',
    tags: ['vegetarian', 'vegan', 'healthy', 'budget'],
    nutrition: { kcal: 290, protein: 15, fat: 7, carbs: 44 },
    ingredients: [
      { name: 'Квасоля', normalizedName: 'квасоля', quantity: 400, unit: 'г', approxPricePerUnit: 7 },
      { name: 'Картопля', normalizedName: 'картопля', quantity: 300, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Морква', normalizedName: 'морква', quantity: 100, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 1, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Томатна паста', normalizedName: 'томатна паста', quantity: 40, unit: 'г', approxPricePerUnit: 12 },
      { name: 'Олія', normalizedName: 'олія', quantity: 2, unit: 'ст.л', approxPricePerUnit: 6 },
    ],
    steps: [
      { step: 1, text: 'Якщо квасоля суха — замочіть із вечора; консервовану просто промийте.' },
      { step: 2, text: 'Відваріть картоплю в 2 л води.', timerMinutes: 15 },
      { step: 3, text: 'Спасеруйте цибулю з морквою й томатною пастою.', timerMinutes: 8 },
      { step: 4, text: 'Додайте квасолю і засмажку, доваріть.', timerMinutes: 12 },
    ],
  },
  {
    id: 'r-zapechena-kurka',
    slug: 'kurka-zapechena-z-kartopleiu',
    title: 'Курка, запечена з картоплею',
    summary: 'Класика вихідного дня: одне деко, мінімум роботи.',
    servings: 4,
    cookingTime: 70,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'dinner',
    imageEmoji: '🍗',
    tags: ['high-protein', 'comfort', 'batch-cook'],
    nutrition: { kcal: 560, protein: 38, fat: 26, carbs: 42 },
    ingredients: [
      { name: 'Куряче філе', normalizedName: 'куряче філе', quantity: 700, unit: 'г', approxPricePerUnit: 25 },
      { name: 'Картопля', normalizedName: 'картопля', quantity: 800, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 2, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Часник', normalizedName: 'часник', quantity: 4, unit: 'шт', approxPricePerUnit: 300 },
      { name: 'Олія', normalizedName: 'олія', quantity: 3, unit: 'ст.л', approxPricePerUnit: 6 },
      { name: 'Сметана', normalizedName: 'сметана', quantity: 100, unit: 'г', approxPricePerUnit: 15, optional: true },
    ],
    steps: [
      { step: 1, text: 'Замаринуйте мʼясо в олії з часником і сіллю.', timerMinutes: 15 },
      { step: 2, text: 'Наріжте картоплю великими шматками, викладіть на деко.' },
      { step: 3, text: 'Зверху покладіть мʼясо, накрийте фольгою.' },
      { step: 4, text: 'Запікайте при 200 °C під фольгою.', timerMinutes: 35 },
      { step: 5, text: 'Зніміть фольгу й допечіть до рум’яності.', timerMinutes: 15 },
    ],
  },
  {
    id: 'r-smuzi',
    slug: 'smuzi-z-bananom',
    title: 'Смузі з бананом і йогуртом',
    summary: 'Дві хвилини й жодного вогню. Рятує фрукти, що перестигли.',
    servings: 2,
    cookingTime: 5,
    difficulty: 'easy',
    cuisine: 'Американська',
    mealType: 'snack',
    imageEmoji: '🥤',
    tags: ['vegetarian', 'healthy', 'quick', 'no-cook', 'kid-friendly', 'rescue'],
    nutrition: { kcal: 210, protein: 9, fat: 4, carbs: 36 },
    ingredients: [
      { name: 'Банани', normalizedName: 'банани', quantity: 2, unit: 'шт', approxPricePerUnit: 1200 },
      { name: 'Йогурт', normalizedName: 'йогурт', quantity: 300, unit: 'г', approxPricePerUnit: 12, substitutes: ['молоко'] },
      { name: 'Мед', normalizedName: 'мед', quantity: 20, unit: 'г', approxPricePerUnit: 25, optional: true },
      { name: 'Вівсянка', normalizedName: 'вівсянка', quantity: 30, unit: 'г', approxPricePerUnit: 5, optional: true },
    ],
    steps: [
      { step: 1, text: 'Складіть усе в блендер.' },
      { step: 2, text: 'Збийте до однорідності.', timerMinutes: 1 },
    ],
  },
  {
    id: 'r-bruschetta',
    slug: 'brusketa-z-pomidoramy',
    title: 'Брускета з помідорами',
    summary: 'Перекус із черствого хліба та помідорів, яким лишився день.',
    servings: 2,
    cookingTime: 12,
    difficulty: 'easy',
    cuisine: 'Італійська',
    mealType: 'snack',
    imageEmoji: '🍅',
    tags: ['vegetarian', 'vegan', 'quick', 'rescue', 'budget'],
    nutrition: { kcal: 240, protein: 6, fat: 10, carbs: 32 },
    ingredients: [
      { name: 'Хліб', normalizedName: 'хліб', quantity: 4, unit: 'шт', approxPricePerUnit: 600 },
      { name: 'Помідори', normalizedName: 'помідори', quantity: 3, unit: 'шт', approxPricePerUnit: 1200 },
      { name: 'Часник', normalizedName: 'часник', quantity: 2, unit: 'шт', approxPricePerUnit: 300 },
      { name: 'Олія', normalizedName: 'олія', quantity: 2, unit: 'ст.л', approxPricePerUnit: 6 },
    ],
    steps: [
      { step: 1, text: 'Підсушіть хліб на сухій сковороді до хрусткої скоринки.', timerMinutes: 4 },
      { step: 2, text: 'Натріть теплий хліб розрізаним зубчиком часнику.' },
      { step: 3, text: 'Наріжте помідори дрібним кубиком, посоліть, злийте сік.' },
      { step: 4, text: 'Викладіть на хліб і полийте олією.' },
    ],
  },
  // ── Додано 02.09: книга була перекошена у вечері (13 із 30), а десертів
  // і перекусів бракувало настільки, що фільтр «Десерт» давав дві страви.
  // Усі інгредієнти — з канонічного словника, інакше агент не зіставить
  // рецепт із коморою й виключить його з підбору.
  {
    id: 'r-zapikanka-syrna',
    slug: 'zapikanka-syrna',
    title: 'Сирна запіканка',
    summary: 'Рятує сир, якому лишився день. Готується без нагляду — двадцять хвилин у духовці.',
    servings: 4,
    cookingTime: 40,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'dessert',
    imageEmoji: '🍮',
    tags: ['vegetarian', 'kid-friendly'],
    nutrition: { kcal: 310, protein: 19, fat: 11, carbs: 34 },
    ingredients: [
      { name: 'Сир кисломолочний', normalizedName: 'сир кисломолочний', quantity: 500, unit: 'г', approxPricePerUnit: 20 },
      { name: 'Яйця', normalizedName: 'яйця', quantity: 2, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Манка', normalizedName: 'манка', quantity: 60, unit: 'г', approxPricePerUnit: 4 },
      { name: 'Цукор', normalizedName: 'цукор', quantity: 60, unit: 'г', approxPricePerUnit: 4 },
      { name: 'Родзинки', normalizedName: 'родзинки', quantity: 50, unit: 'г', approxPricePerUnit: 20, optional: true },
      { name: 'Сметана', normalizedName: 'сметана', quantity: 100, unit: 'г', approxPricePerUnit: 15, optional: true },
    ],
    steps: [
      { step: 1, text: 'Змішайте сир із яйцями, цукром і манкою, лишіть на десять хвилин — манка має набубнявіти.', timerMinutes: 10 },
      { step: 2, text: 'Додайте родзинки, попередньо залиті окропом на пʼять хвилин.' },
      { step: 3, text: 'Викладіть у форму, розрівняйте й змастіть сметаною.' },
      { step: 4, text: 'Випікайте при 180 градусах до золотої скоринки.', timerMinutes: 30 },
    ],
  },
  {
    id: 'r-mlyntsi-moloko',
    slug: 'mlyntsi-na-moloci',
    title: 'Млинці на молоці',
    summary: 'Сніданок із трьох продуктів, які майже завжди є. Тісто готове за пʼять хвилин.',
    servings: 4,
    cookingTime: 30,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'breakfast',
    imageEmoji: '🥞',
    tags: ['vegetarian', 'kid-friendly'],
    nutrition: { kcal: 280, protein: 9, fat: 9, carbs: 40 },
    ingredients: [
      { name: 'Борошно', normalizedName: 'борошно', quantity: 250, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Молоко', normalizedName: 'молоко', quantity: 500, unit: 'мл', approxPricePerUnit: 5 },
      { name: 'Яйця', normalizedName: 'яйця', quantity: 2, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Цукор', normalizedName: 'цукор', quantity: 30, unit: 'г', approxPricePerUnit: 4 },
      { name: 'Олія', normalizedName: 'олія', quantity: 2, unit: 'ст.л', approxPricePerUnit: 6 },
    ],
    steps: [
      { step: 1, text: 'Збийте яйця з цукром, влийте половину молока.' },
      { step: 2, text: 'Просійте борошно й вимішайте до однорідності, потім долийте решту молока.' },
      { step: 3, text: 'Дайте тісту постояти — клейковина розслабиться, млинці не рватимуться.', timerMinutes: 15 },
      { step: 4, text: 'Смажте на добре розігрітій сковороді по хвилині з боку.', timerMinutes: 12 },
    ],
  },
  {
    id: 'r-tost-avokado',
    slug: 'tost-avokado-yaitse',
    title: 'Тост з авокадо та яйцем',
    summary: 'Сніданок на одну сковорідку й пʼять хвилин, коли готувати немає коли.',
    servings: 2,
    cookingTime: 10,
    difficulty: 'easy',
    cuisine: 'Американська',
    mealType: 'breakfast',
    imageEmoji: '🥑',
    tags: ['vegetarian', 'quick'],
    nutrition: { kcal: 340, protein: 14, fat: 22, carbs: 24 },
    ingredients: [
      { name: 'Хліб', normalizedName: 'хліб', quantity: 2, unit: 'шт', approxPricePerUnit: 600 },
      { name: 'Авокадо', normalizedName: 'авокадо', quantity: 1, unit: 'шт', approxPricePerUnit: 6000 },
      { name: 'Яйця', normalizedName: 'яйця', quantity: 2, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Лимон', normalizedName: 'лимон', quantity: 1, unit: 'шт', approxPricePerUnit: 1500, optional: true },
    ],
    steps: [
      { step: 1, text: 'Підсушіть хліб на сухій сковороді до хрусткої скоринки.', timerMinutes: 3 },
      { step: 2, text: 'Розімніть авокадо виделкою, посоліть і скропіть лимоном — так воно не потемніє.' },
      { step: 3, text: 'Підсмажте яйця так, як любите: жовток рідким або повністю схопленим.', timerMinutes: 4 },
      { step: 4, text: 'Викладіть авокадо на тост, зверху — яйце.' },
    ],
  },
  {
    id: 'r-vivsyane-pechyvo',
    slug: 'vivsyane-pechyvo',
    title: 'Вівсяне печиво з медом',
    summary: 'Перекус, який можна взяти з собою. Без форми й міксера — ложкою на деко.',
    servings: 6,
    cookingTime: 35,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'snack',
    imageEmoji: '🍪',
    tags: ['vegetarian', 'kid-friendly'],
    nutrition: { kcal: 220, protein: 5, fat: 9, carbs: 31 },
    ingredients: [
      { name: 'Вівсянка', normalizedName: 'вівсянка', quantity: 200, unit: 'г', approxPricePerUnit: 5 },
      { name: 'Борошно', normalizedName: 'борошно', quantity: 80, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Мед', normalizedName: 'мед', quantity: 60, unit: 'г', approxPricePerUnit: 25 },
      { name: 'Масло вершкове', normalizedName: 'масло вершкове', quantity: 80, unit: 'г', approxPricePerUnit: 40 },
      { name: 'Яйця', normalizedName: 'яйця', quantity: 1, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Родзинки', normalizedName: 'родзинки', quantity: 60, unit: 'г', approxPricePerUnit: 20, optional: true },
    ],
    steps: [
      { step: 1, text: 'Розтопіть масло й змішайте з медом.' },
      { step: 2, text: 'Додайте яйце, вівсянку, борошно й родзинки, вимішайте.' },
      { step: 3, text: 'Викладайте ложкою на пергамент, лишаючи місце — печиво розпливеться.' },
      { step: 4, text: 'Випікайте при 180 градусах до румʼяних країв.', timerMinutes: 18 },
    ],
  },
  {
    id: 'r-ovocheve-ragu',
    slug: 'ovocheve-ragu',
    title: 'Овочеве рагу',
    summary: 'Складається з того, що доживає в овочевому ящику. Пропорції вільні.',
    servings: 4,
    cookingTime: 40,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'dinner',
    imageEmoji: '🍲',
    tags: ['vegetarian', 'vegan'],
    nutrition: { kcal: 190, protein: 5, fat: 8, carbs: 27 },
    ingredients: [
      { name: 'Кабачки', normalizedName: 'кабачки', quantity: 400, unit: 'г', approxPricePerUnit: 4 },
      { name: 'Баклажани', normalizedName: 'баклажани', quantity: 300, unit: 'г', approxPricePerUnit: 6 },
      { name: 'Помідори', normalizedName: 'помідори', quantity: 3, unit: 'шт', approxPricePerUnit: 1200 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 1, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Морква', normalizedName: 'морква', quantity: 150, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Олія', normalizedName: 'олія', quantity: 3, unit: 'ст.л', approxPricePerUnit: 6 },
    ],
    steps: [
      { step: 1, text: 'Баклажани наріжте кубиком, посоліть і лишіть на десять хвилин, потім злийте гіркий сік.', timerMinutes: 10 },
      { step: 2, text: 'Обсмажте цибулю з морквою до мʼякості.', timerMinutes: 6 },
      { step: 3, text: 'Додайте кабачки й баклажани, тушкуйте під кришкою.', timerMinutes: 15 },
      { step: 4, text: 'Додайте помідори й доведіть до готовності без кришки, щоб зайва вода випарувалась.', timerMinutes: 8 },
    ],
  },
  {
    id: 'r-sup-kuryachyi',
    slug: 'sup-kuryachyi-z-lokshynoyu',
    title: 'Курячий суп з локшиною',
    summary: 'Одна каструля на всю родину, і на другий день смачніше.',
    servings: 4,
    cookingTime: 45,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'lunch',
    imageEmoji: '🍜',
    tags: ['kid-friendly'],
    nutrition: { kcal: 290, protein: 24, fat: 8, carbs: 30 },
    ingredients: [
      { name: 'Куряче філе', normalizedName: 'куряче філе', quantity: 400, unit: 'г', approxPricePerUnit: 25 },
      { name: 'Макарони', normalizedName: 'макарони', quantity: 120, unit: 'г', approxPricePerUnit: 8 },
      { name: 'Картопля', normalizedName: 'картопля', quantity: 300, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Морква', normalizedName: 'морква', quantity: 150, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 1, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Кріп', normalizedName: 'кріп', quantity: 20, unit: 'г', approxPricePerUnit: 25, optional: true },
    ],
    steps: [
      { step: 1, text: 'Залийте філе холодною водою й варіть на малому вогні, знімаючи піну.', timerMinutes: 25 },
      { step: 2, text: 'Вийміть мʼясо, закладіть картоплю й моркву.', timerMinutes: 10 },
      { step: 3, text: 'Додайте локшину й розібране на волокна мʼясо.', timerMinutes: 7 },
      { step: 4, text: 'Зніміть з вогню, додайте кріп і дайте настоятись під кришкою.', timerMinutes: 5 },
    ],
  },
  {
    id: 'r-salat-tunets',
    slug: 'salat-z-tuntsem',
    title: 'Салат із тунцем',
    summary: 'Обід без плити: усе з банки й холодильника, пʼятнадцять хвилин.',
    servings: 2,
    cookingTime: 15,
    difficulty: 'easy',
    cuisine: 'Середземноморська',
    mealType: 'lunch',
    imageEmoji: '🥗',
    tags: ['quick'],
    nutrition: { kcal: 330, protein: 26, fat: 18, carbs: 15 },
    ingredients: [
      { name: 'Тунець', normalizedName: 'тунець', quantity: 150, unit: 'г', approxPricePerUnit: 45 },
      { name: 'Яйця', normalizedName: 'яйця', quantity: 2, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Кукурудза', normalizedName: 'кукурудза', quantity: 100, unit: 'г', approxPricePerUnit: 12 },
      { name: 'Огірки', normalizedName: 'огірки', quantity: 1, unit: 'шт', approxPricePerUnit: 1000 },
      { name: 'Майонез', normalizedName: 'майонез', quantity: 40, unit: 'г', approxPricePerUnit: 12, optional: true },
    ],
    steps: [
      { step: 1, text: 'Зваріть яйця круто й остудіть у холодній воді — так шкаралупа знімається чисто.', timerMinutes: 9 },
      { step: 2, text: 'Злийте рідину з тунця й розберіть його виделкою.' },
      { step: 3, text: 'Наріжте яйця й огірок кубиком, змішайте з кукурудзою.' },
      { step: 4, text: 'Заправте майонезом і посоліть за смаком.' },
    ],
  },
  {
    id: 'r-plov-kurka',
    slug: 'plov-z-kurkoyu',
    title: 'Плов з куркою',
    summary: 'Вечеря на казан: рис вбирає все, що встигло підсмажитись.',
    servings: 4,
    cookingTime: 50,
    difficulty: 'medium',
    cuisine: 'Азійська',
    mealType: 'dinner',
    imageEmoji: '🍚',
    tags: ['kid-friendly'],
    nutrition: { kcal: 480, protein: 27, fat: 14, carbs: 62 },
    ingredients: [
      { name: 'Рис', normalizedName: 'рис', quantity: 300, unit: 'г', approxPricePerUnit: 6 },
      { name: 'Куряче філе', normalizedName: 'куряче філе', quantity: 400, unit: 'г', approxPricePerUnit: 25 },
      { name: 'Морква', normalizedName: 'морква', quantity: 200, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 1, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Часник', normalizedName: 'часник', quantity: 3, unit: 'шт', approxPricePerUnit: 300 },
      { name: 'Олія', normalizedName: 'олія', quantity: 4, unit: 'ст.л', approxPricePerUnit: 6 },
    ],
    steps: [
      { step: 1, text: 'Промийте рис до прозорої води — інакше плов злипнеться.' },
      { step: 2, text: 'Обсмажте курку до скоринки, додайте цибулю й моркву соломкою.', timerMinutes: 12 },
      { step: 3, text: 'Викладіть рис рівним шаром, залийте окропом на два пальці вище, вкиньте зубчики часнику.' },
      { step: 4, text: 'Варіть без кришки, доки вода не зрівняється з рисом, потім накрийте й тримайте на малому вогні.', timerMinutes: 25 },
    ],
  },
  {
    id: 'r-krem-sup-harbuz',
    slug: 'krem-sup-harbuzovyi',
    title: 'Гарбузовий крем-суп',
    summary: 'Осінній обід, який рятує гарбуз, що не влазить у холодильник.',
    servings: 4,
    cookingTime: 35,
    difficulty: 'easy',
    cuisine: 'Середземноморська',
    mealType: 'lunch',
    imageEmoji: '🎃',
    tags: ['vegetarian'],
    nutrition: { kcal: 210, protein: 5, fat: 11, carbs: 25 },
    ingredients: [
      { name: 'Гарбуз', normalizedName: 'гарбуз', quantity: 600, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Картопля', normalizedName: 'картопля', quantity: 200, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 1, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Вершки', normalizedName: 'вершки', quantity: 100, unit: 'мл', approxPricePerUnit: 12 },
      { name: 'Олія', normalizedName: 'олія', quantity: 2, unit: 'ст.л', approxPricePerUnit: 6 },
    ],
    steps: [
      { step: 1, text: 'Обсмажте цибулю на олії до прозорості.', timerMinutes: 5 },
      { step: 2, text: 'Додайте кубики гарбуза й картоплі, залийте окропом урівень і варіть до мʼякості.', timerMinutes: 20 },
      { step: 3, text: 'Збийте блендером, доливаючи відвар до потрібної густини.' },
      { step: 4, text: 'Влийте вершки, прогрійте не доводячи до кипіння.', timerMinutes: 3 },
    ],
  },
  {
    id: 'r-ryba-zapechena',
    slug: 'ryba-zapechena-z-ovochamy',
    title: 'Риба, запечена з овочами',
    summary: 'Одне деко, жодного смаження: вечеря готується сама, поки накриваєте стіл.',
    servings: 3,
    cookingTime: 45,
    difficulty: 'easy',
    cuisine: 'Середземноморська',
    mealType: 'dinner',
    imageEmoji: '🐟',
    tags: [],
    nutrition: { kcal: 360, protein: 30, fat: 14, carbs: 28 },
    ingredients: [
      { name: 'Риба', normalizedName: 'риба', quantity: 500, unit: 'г', approxPricePerUnit: 35 },
      { name: 'Картопля', normalizedName: 'картопля', quantity: 400, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Морква', normalizedName: 'морква', quantity: 150, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Лимон', normalizedName: 'лимон', quantity: 1, unit: 'шт', approxPricePerUnit: 1500 },
      { name: 'Олія', normalizedName: 'олія', quantity: 3, unit: 'ст.л', approxPricePerUnit: 6 },
    ],
    steps: [
      { step: 1, text: 'Наріжте картоплю тонкими кружальцями, моркву — соломкою, викладіть на деко з олією.' },
      { step: 2, text: 'Запікайте овочі при 200 градусах, поки картопля не почне мʼякшати.', timerMinutes: 20 },
      { step: 3, text: 'Викладіть рибу зверху, скропіть лимоном і посоліть.' },
      { step: 4, text: 'Поверніть у духовку до готовності риби — мʼякоть має легко відходити виделкою.', timerMinutes: 18 },
    ],
  },
  {
    id: 'r-yohurt-desert',
    slug: 'yohurtovyi-desert-z-yahodamy',
    title: 'Йогуртовий десерт з ягодами',
    summary: 'Десерт без випікання: збирається за пʼять хвилин із замороженого й того, що є.',
    servings: 2,
    cookingTime: 10,
    difficulty: 'easy',
    cuisine: 'Американська',
    mealType: 'dessert',
    imageEmoji: '🫐',
    tags: ['vegetarian', 'quick', 'kid-friendly'],
    nutrition: { kcal: 260, protein: 11, fat: 9, carbs: 34 },
    ingredients: [
      { name: 'Йогурт', normalizedName: 'йогурт', quantity: 300, unit: 'г', approxPricePerUnit: 12 },
      { name: 'Заморожені ягоди', normalizedName: 'заморожені ягоди', quantity: 150, unit: 'г', approxPricePerUnit: 20 },
      { name: 'Мед', normalizedName: 'мед', quantity: 30, unit: 'г', approxPricePerUnit: 25 },
      { name: 'Горіхи', normalizedName: 'горіхи', quantity: 30, unit: 'г', approxPricePerUnit: 60, optional: true },
    ],
    steps: [
      { step: 1, text: 'Дайте ягодам відтанути на дві третини — так вони пустять сік, але не перетворяться на кашу.', timerMinutes: 8 },
      { step: 2, text: 'Змішайте йогурт із медом.' },
      { step: 3, text: 'Викладіть шарами в склянки, зверху — подрібнені горіхи.' },
    ],
  },
  {
    id: 'r-humus',
    slug: 'humus-domashniy',
    title: 'Домашній хумус',
    summary: 'Перекус, який стоїть у холодильнику тиждень і рятує будь-який хліб.',
    servings: 4,
    cookingTime: 15,
    difficulty: 'easy',
    cuisine: 'Середземноморська',
    mealType: 'snack',
    imageEmoji: '🫓',
    tags: ['vegetarian', 'vegan'],
    nutrition: { kcal: 240, protein: 9, fat: 13, carbs: 24 },
    ingredients: [
      { name: 'Нут', normalizedName: 'нут', quantity: 400, unit: 'г', approxPricePerUnit: 8 },
      { name: 'Олія оливкова', normalizedName: 'олія оливкова', quantity: 60, unit: 'мл', approxPricePerUnit: 25 },
      { name: 'Часник', normalizedName: 'часник', quantity: 2, unit: 'шт', approxPricePerUnit: 300 },
      { name: 'Лимон', normalizedName: 'лимон', quantity: 1, unit: 'шт', approxPricePerUnit: 1500 },
    ],
    steps: [
      { step: 1, text: 'Злийте рідину з нуту, але лишіть півсклянки — вона знадобиться для густини.' },
      { step: 2, text: 'Збийте нут із часником, олією та соком лимона до однорідності.' },
      { step: 3, text: 'Доливайте залишену рідину по ложці, доки не стане кремовим.' },
    ],
  },
]

/** Рецепти з приклеєними порадами — саме це експортується назовні. */
export const SEED_RECIPES: RecipeLike[] = RAW_RECIPES.map((recipe) => ({
  ...recipe,
  tips: RECIPE_TIPS[recipe.id] ?? [],
}))
