import type { RecipeLike } from '@/lib/domain/types'

/**
 * Базова книга рецептів для demo mode.
 * У live-режимі агент доповнює її згенерованими Claude рецептами,
 * але ці лишаються як детермінована основа демонстрації.
 */
export const SEED_RECIPES: RecipeLike[] = [
  {
    id: 'r-pasta-spinach',
    slug: 'pasta-shpynat-pomidory',
    title: 'Паста зі шпинатом і помідорами',
    summary: 'Швидка вечеря з того, що вже є вдома. Шпинат встигає піти у справу.',
    servings: 2,
    cookingTime: 25,
    difficulty: 'easy',
    cuisine: 'Італійська',
    mealType: 'dinner',
    imageEmoji: '🍝',
    tags: ['vegetarian', 'kid-friendly', 'quick'],
    nutrition: { kcal: 520, protein: 18, fat: 16, carbs: 74 },
    ingredients: [
      { name: 'Макарони', normalizedName: 'макарони', quantity: 250, unit: 'г', approxPricePerUnit: 8 },
      { name: 'Шпинат', normalizedName: 'шпинат', quantity: 150, unit: 'г', approxPricePerUnit: 30, substitutes: ['салат'] },
      { name: 'Помідори', normalizedName: 'помідори', quantity: 3, unit: 'шт', approxPricePerUnit: 1200 },
      { name: 'Часник', normalizedName: 'часник', quantity: 2, unit: 'шт', approxPricePerUnit: 300, optional: true },
      { name: 'Олія', normalizedName: 'олія', quantity: 2, unit: 'ст.л', approxPricePerUnit: 6 },
      { name: 'Сир твердий', normalizedName: 'сир твердий', quantity: 50, unit: 'г', approxPricePerUnit: 45, optional: true },
    ],
    steps: [
      { step: 1, text: 'Закипʼятіть підсолену воду і відваріть макарони до al dente.', timerMinutes: 9 },
      { step: 2, text: 'Наріжте помідори кубиком, часник — тонкими пластинками.' },
      { step: 3, text: 'Розігрійте олію, обсмажте часник 30 секунд, додайте помідори.', timerMinutes: 4 },
      { step: 4, text: 'Додайте шпинат і готуйте, доки він не осяде.', timerMinutes: 3 },
      { step: 5, text: 'Змішайте з макаронами, за бажанням присипте тертим сиром.' },
    ],
  },
  {
    id: 'r-frittata',
    slug: 'frytata-zi-shpynatom',
    title: 'Фрітата зі шпинатом',
    summary: 'Пʼять інгредієнтів, одна сковорідка, 20 хвилин.',
    servings: 2,
    cookingTime: 20,
    difficulty: 'easy',
    cuisine: 'Італійська',
    mealType: 'dinner',
    imageEmoji: '🍳',
    tags: ['vegetarian', 'kid-friendly', 'quick', 'high-protein'],
    nutrition: { kcal: 340, protein: 24, fat: 23, carbs: 6 },
    ingredients: [
      { name: 'Яйця', normalizedName: 'яйця', quantity: 4, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Шпинат', normalizedName: 'шпинат', quantity: 120, unit: 'г', approxPricePerUnit: 30 },
      { name: 'Молоко', normalizedName: 'молоко', quantity: 60, unit: 'мл', approxPricePerUnit: 5 },
      { name: 'Масло вершкове', normalizedName: 'масло вершкове', quantity: 20, unit: 'г', approxPricePerUnit: 40 },
      { name: 'Помідори', normalizedName: 'помідори', quantity: 2, unit: 'шт', approxPricePerUnit: 1200, optional: true },
      { name: 'Сир твердий', normalizedName: 'сир твердий', quantity: 40, unit: 'г', approxPricePerUnit: 45, optional: true },
    ],
    steps: [
      { step: 1, text: 'Збийте яйця з молоком, посоліть.' },
      { step: 2, text: 'Розтопіть масло, підсмажте шпинат до розмʼякшення.', timerMinutes: 3 },
      { step: 3, text: 'Влийте яйця, готуйте на малому вогні під кришкою.', timerMinutes: 10 },
      { step: 4, text: 'За бажанням додайте помідори й сир, дайте розплавитись.', timerMinutes: 2 },
    ],
  },
  {
    id: 'r-tiramisu',
    slug: 'tiramisu',
    title: 'Тірамісу',
    summary: 'Класичний італійський десерт із маскарпоне та кавою. Без випікання.',
    servings: 6,
    cookingTime: 30,
    difficulty: 'medium',
    cuisine: 'Італійська',
    mealType: 'dessert',
    imageEmoji: '🍰',
    tags: ['dessert', 'no-bake', 'coffee'],
    nutrition: { kcal: 450, protein: 8, fat: 28, carbs: 40 },
    ingredients: [
      { name: 'Маскарпоне', normalizedName: 'маскарпоне', quantity: 500, unit: 'г', approxPricePerUnit: 60 },
      { name: 'Печиво савоярді', normalizedName: 'савоярді', quantity: 200, unit: 'г', approxPricePerUnit: 50 },
      { name: 'Яйця', normalizedName: 'яйця', quantity: 4, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Цукор', normalizedName: 'цукор', quantity: 100, unit: 'г', approxPricePerUnit: 4 },
      // мелена кава вимірюється у грамах: 30 г дають ~300 мл міцної кави.
      // Тримати тут «300 мл» означало б порівнювати обʼєм напою з масою упаковки.
      { name: 'Кава мелена', normalizedName: 'кава', quantity: 30, unit: 'г', approxPricePerUnit: 60 },
      { name: 'Какао', normalizedName: 'какао', quantity: 20, unit: 'г', approxPricePerUnit: 55 },
    ],
    steps: [
      { step: 1, text: 'Зваріть із 30 г меленої кави ~300 мл міцної кави і повністю охолодіть.', timerMinutes: 10 },
      { step: 2, text: 'Відділіть жовтки, збийте їх із цукром до світлої маси.', timerMinutes: 5 },
      { step: 3, text: 'Вмішайте маскарпоне до однорідності.' },
      { step: 4, text: 'Збийте білки до стійких піків і обережно вмішайте в крем.', timerMinutes: 4 },
      { step: 5, text: 'Занурюйте савоярді в каву на 1–2 секунди й викладайте шаром.' },
      { step: 6, text: 'Чергуйте крем і печиво, зверху присипте какао.' },
      { step: 7, text: 'Охолоджуйте в холодильнику щонайменше 4 години.', timerMinutes: 240 },
    ],
  },
  {
    id: 'r-omlet',
    slug: 'omlet-z-pomidoramy',
    title: 'Омлет з помідорами',
    summary: 'Найшвидший спосіб нагодувати родину з того, що є в холодильнику.',
    servings: 2,
    cookingTime: 12,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'breakfast',
    imageEmoji: '🍳',
    tags: ['vegetarian', 'kid-friendly', 'quick'],
    nutrition: { kcal: 280, protein: 18, fat: 20, carbs: 5 },
    ingredients: [
      { name: 'Яйця', normalizedName: 'яйця', quantity: 4, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Молоко', normalizedName: 'молоко', quantity: 80, unit: 'мл', approxPricePerUnit: 5 },
      { name: 'Помідори', normalizedName: 'помідори', quantity: 2, unit: 'шт', approxPricePerUnit: 1200 },
      { name: 'Масло вершкове', normalizedName: 'масло вершкове', quantity: 15, unit: 'г', approxPricePerUnit: 40 },
    ],
    steps: [
      { step: 1, text: 'Збийте яйця з молоком і дрібкою солі.' },
      { step: 2, text: 'Обсмажте помідори на маслі 2 хвилини.', timerMinutes: 2 },
      { step: 3, text: 'Влийте яєчну суміш, накрийте кришкою.', timerMinutes: 6 },
    ],
  },
  {
    id: 'r-mac-cheese',
    slug: 'makarony-z-syrom',
    title: 'Макарони із сирним соусом',
    summary: 'Дитяча класика: без гострого, готується у пʼять кроків.',
    servings: 3,
    cookingTime: 25,
    difficulty: 'easy',
    cuisine: 'Американська',
    mealType: 'lunch',
    imageEmoji: '🧀',
    tags: ['vegetarian', 'kid-friendly', 'comfort'],
    nutrition: { kcal: 610, protein: 22, fat: 26, carbs: 72 },
    ingredients: [
      { name: 'Макарони', normalizedName: 'макарони', quantity: 300, unit: 'г', approxPricePerUnit: 8 },
      { name: 'Молоко', normalizedName: 'молоко', quantity: 250, unit: 'мл', approxPricePerUnit: 5 },
      { name: 'Сир твердий', normalizedName: 'сир твердий', quantity: 150, unit: 'г', approxPricePerUnit: 45 },
      { name: 'Масло вершкове', normalizedName: 'масло вершкове', quantity: 30, unit: 'г', approxPricePerUnit: 40 },
      { name: 'Борошно', normalizedName: 'борошно', quantity: 20, unit: 'г', approxPricePerUnit: 3 },
    ],
    steps: [
      { step: 1, text: 'Відваріть макарони.', timerMinutes: 9 },
      { step: 2, text: 'Розтопіть масло, вмішайте борошно, прогрійте хвилину.', timerMinutes: 1 },
      { step: 3, text: 'Поступово влийте молоко, помішуючи до загустіння.', timerMinutes: 4 },
      { step: 4, text: 'Додайте тертий сир, розмішайте до однорідності.' },
      { step: 5, text: 'Змішайте соус із макаронами.' },
    ],
  },
  {
    id: 'r-chicken-veg',
    slug: 'kuryache-file-z-ovochamy',
    title: 'Куряче філе з овочами на сковороді',
    summary: 'Збалансована вечеря на двох за 30 хвилин.',
    servings: 2,
    cookingTime: 30,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'dinner',
    imageEmoji: '🍗',
    tags: ['high-protein', 'kid-friendly'],
    nutrition: { kcal: 430, protein: 42, fat: 15, carbs: 22 },
    ingredients: [
      { name: 'Куряче філе', normalizedName: 'куряче філе', quantity: 400, unit: 'г', approxPricePerUnit: 25 },
      { name: 'Помідори', normalizedName: 'помідори', quantity: 2, unit: 'шт', approxPricePerUnit: 1200 },
      { name: 'Цибуля', normalizedName: 'цибуля', quantity: 1, unit: 'шт', approxPricePerUnit: 800 },
      { name: 'Олія', normalizedName: 'олія', quantity: 2, unit: 'ст.л', approxPricePerUnit: 6 },
      { name: 'Шпинат', normalizedName: 'шпинат', quantity: 100, unit: 'г', approxPricePerUnit: 30, optional: true },
    ],
    steps: [
      { step: 1, text: 'Наріжте філе смужками, посоліть.' },
      { step: 2, text: 'Обсмажте на сильному вогні до рум’яності.', timerMinutes: 7 },
      { step: 3, text: 'Додайте цибулю й помідори, тушкуйте.', timerMinutes: 10 },
      { step: 4, text: 'Наприкінці вкиньте шпинат і вимкніть вогонь.', timerMinutes: 2 },
    ],
  },
  {
    id: 'r-syrnyky',
    slug: 'syrnyky',
    title: 'Сирники',
    summary: 'Сніданок, який любить уся родина.',
    servings: 3,
    cookingTime: 25,
    difficulty: 'easy',
    cuisine: 'Українська',
    mealType: 'breakfast',
    imageEmoji: '🥞',
    tags: ['vegetarian', 'kid-friendly', 'sweet'],
    nutrition: { kcal: 390, protein: 24, fat: 14, carbs: 40 },
    ingredients: [
      { name: 'Сир кисломолочний', normalizedName: 'сир кисломолочний', quantity: 400, unit: 'г', approxPricePerUnit: 20 },
      { name: 'Яйця', normalizedName: 'яйця', quantity: 2, unit: 'шт', approxPricePerUnit: 700 },
      { name: 'Борошно', normalizedName: 'борошно', quantity: 60, unit: 'г', approxPricePerUnit: 3 },
      { name: 'Цукор', normalizedName: 'цукор', quantity: 40, unit: 'г', approxPricePerUnit: 4 },
      { name: 'Сметана', normalizedName: 'сметана', quantity: 100, unit: 'г', approxPricePerUnit: 15, optional: true },
    ],
    steps: [
      { step: 1, text: 'Розімніть сир з яйцями та цукром.' },
      { step: 2, text: 'Додайте борошно, замісіть мʼяке тісто.' },
      { step: 3, text: 'Сформуйте сирники й обсмажте з двох боків.', timerMinutes: 10 },
    ],
  },
  {
    id: 'r-spicy-noodles',
    slug: 'gostri-locshyna',
    title: 'Гостра локшина по-азійськи',
    summary: 'Для тих, хто любить гостре. Готується за 20 хвилин.',
    servings: 2,
    cookingTime: 20,
    difficulty: 'easy',
    cuisine: 'Азійська',
    mealType: 'dinner',
    imageEmoji: '🌶️',
    tags: ['spicy', 'quick'],
    nutrition: { kcal: 480, protein: 16, fat: 14, carbs: 72 },
    ingredients: [
      { name: 'Макарони', normalizedName: 'макарони', quantity: 200, unit: 'г', approxPricePerUnit: 8 },
      { name: 'Куряче філе', normalizedName: 'куряче філе', quantity: 200, unit: 'г', approxPricePerUnit: 25 },
      { name: 'Соєвий соус', normalizedName: 'соєвий соус', quantity: 40, unit: 'мл', approxPricePerUnit: 20 },
      { name: 'Часник', normalizedName: 'часник', quantity: 3, unit: 'шт', approxPricePerUnit: 300 },
    ],
    steps: [
      { step: 1, text: 'Відваріть локшину.', timerMinutes: 7 },
      { step: 2, text: 'Обсмажте курку з часником і гострим перцем.', timerMinutes: 8 },
      { step: 3, text: 'Змішайте все із соєвим соусом.' },
    ],
  },
]
